socket-port: 6868
adminPw: ''
valueTimeout: 3000
adminQueries:
- kick
- mem
- tickrate
userQueries:
- serverName
- playerCount
- serverVersion
- playerList
- pluginVersion
disabledQueries: []
