socket-port: 6868
adminPw: ''
adminQueries:
- kick
- mem
- tickrate
userQueries:
- serverName
- playerCount
- serverVersion
- playerList
- pluginVersion
- refresh
- chatHistory
disabledQueries: []
