name: McDesktopInfo
version: ${project.version}
author: Damarus
description: Show information about your server live on your desktop.
website: http://dev.bukkit.org/server-mods/mcdesktopinfo/

load: POSTWORLD
database: false
main: de.damarus.mcdesktopinfo.McDesktopInfo

commands:
  mcdesktopinfo:
    description: Configure McDesktopInfo
    aliases: mcdi

permissions:
  mcdesktopinfo.*:
    description: Grants every mcdesktopinfo permission
    children:
      mcdesktopinfo.admin: true
      mcdesktopinfo.getport: true
      mcdesktopinfo.listQueries: true
  mcdesktopinfo.admin:
    description: Grants access to admin functions
    default: op
  mcdesktopinfo.getport:
    description: Allows the player to use /mcdi port, which displays the socket port
  mcdesktopinfo.listQueries:
    description: Grants access to the /mcdi queries command
