name: McDesktopInfo
version: 0.4.1
author: Damarus
description: Show information about your server live on your desktop.
website: http://dev.bukkit.org/server-mods/mcdesktopinfo/

# Internal stuffz
load: POSTWORLD
database: false
main: de.damarus.mcdesktopinfo.McDesktopInfo

commands:
  mcdesktopinfo:
    description: Configure McDesktopInfo
    aliases: mcdi

permissions:
  mcdesktopinfo.*:
    description: Grants every mcdesktopinfo permission
    children:
      mcdesktopinfo.admin: true
  mcdesktopinfo.admin:
    description: Grants access to admin functions
    default: op